
import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';

// Disable workbox logging
self.__WB_DISABLE_DEV_LOGS = true;

// Precache all assets generated by vite
precacheAndRoute(self.__WB_MANIFEST);

// Cache runtime requests
registerRoute(
  ({ request }) => request.destination === 'script' ||
                   request.destination === 'style' ||
                   request.destination === 'document',
  new StaleWhileRevalidate({
    cacheName: 'static-resources',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 24 * 60 * 60 // 24 hours
      }),
    ],
  })
);

// Skip waiting and claim clients
self.addEventListener('activate', (event) => {
  event.waitUntil(clients.claim());
});
