// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mcwlzrikidzgxexnccju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jd2x6cmlraWR6Z3hleG5jY2p1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgwMTMzMDksImV4cCI6MjA1MzU4OTMwOX0.oBqlkwgx-wEASAfloZw8IFhdlAGIsHNmr7c_r9apo3o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);